### ISSUE TITLE
Add new Package: ui5-cc-timerbutton

### ISSUE THREAD

**Issue by htammen** [ui5-community/bestofui5-data#104]
# Add new NPM Package

https://github.com/htammen/ui5.cc.timerbutton

## Prerequisites

- [X] Add link to your GitHub Repo in `package.json` ([example](https://github.com/ui5-community/ui5-ecosystem-showcase/blob/054d9a6ae2836fdcdef076af765b2cc292082cbd/packages/ui5-tooling-modules/package.json#L7-L11))
- [X] Add a license to your project.
- [X] Add Author to your `package.json` ([example](https://github.com/ui5-community/ui5-ecosystem-showcase/blob/054d9a6ae2836fdcdef076af765b2cc292082cbd/packages/ui5-tooling-modules/package.json#L5)).
- [X] NPM module published with current version.
- [X] `ui5.yaml` file present ([example](https://github.com/ui5-community/ui5-ecosystem-showcase/blob/main/packages/ui5-middleware-livereload/ui5.yaml))

## Pull Request

https://github.com/ui5-community/bestofui5-data/pull/103

**Comment by marianfoo** [comment]
Thank you @htammen for your contribution
The Library was added to the website
![image](https://github.com/ui5-community/bestofui5-data/assets/13335743/0d2c98dd-f3ef-4664-a67a-7448fa701ef6)
