### ISSUE TITLE
Add new Package: ui5-antares

### ISSUE THREAD

**Issue by hasanciftci26** [ui5-community/bestofui5-data#106]
# Add new NPM Package

https://github.com/hasanciftci26/ui5-antares

## Prerequisites

- [x] Add link to your GitHub Repo in `package.json` ([example](https://github.com/ui5-community/ui5-ecosystem-showcase/blob/054d9a6ae2836fdcdef076af765b2cc292082cbd/packages/ui5-tooling-modules/package.json#L7-L11))
- [x] Add a license to your project.
- [x] Add Author to your `package.json` ([example](https://github.com/ui5-community/ui5-ecosystem-showcase/blob/054d9a6ae2836fdcdef076af765b2cc292082cbd/packages/ui5-tooling-modules/package.json#L5)).
- [x] NPM module published with current version.
- [x] `ui5.yaml` file present ([example](https://github.com/ui5-community/ui5-ecosystem-showcase/blob/main/packages/ui5-middleware-livereload/ui5.yaml))

## Pull Request

#105

**Comment by marianfoo** [comment]
added: https://bestofui5.org/#/packages/ui5-antares
