### ISSUE TITLE
openui5-paginator

### ISSUE THREAD

**Issue by wolfe100** [ui5-community/bestofui5-data#67]
{
  "owner": "wolfe100,
  "repo": "openui5-paginator",
  "addedToBoUI5": "2022-07-26T18:22:57.868Z",
  "type": "customControl",
  "tags": ["paginator","openui5","sapui5","sysHUB","ui5","javascript"]
}

**Comment by marianfoo** [comment]
Hi @wolfe100 ,
thank you for your contribution.
Please publish your library on npm.
Then we can add them on bestofui5.
Thanks!

**Comment by wolfe100** [comment]
Hi @marianfoo 
I will do that asap.

**Comment by wolfe100** [comment]
Hi @marianfoo 
The package is now deployed to NPM in the version 1.0.0 with the name
 [openui5-paginator](https://www.npmjs.com/package/openui5-paginator)

Hope that's it.
