### ISSUE TITLE
Add new Package: ui5plugin-parser, ui5plugin-linter

### ISSUE THREAD

**Issue by iljapostnovs** [ui5-community/bestofui5-data#80]
# Add new NPM Package
 Hi.
Please add two packages to the bestofui5.
Seems like prettier automatically formatted source.json together with the push thanks to husky.
Additionally, I've edited tags for my VSCodeUI5Plugin. It was a surprise for me, that it's already here ;)

**Comment by iljapostnovs** [comment]
https://github.com/ui5-community/bestofui5-data/pull/81

**Comment by marianfoo** [comment]
Hey,
thanks for the PR.
I used your VSCodeUI5Plugin to write the VSCode crawler, so it's already there :)
I hope that was ok.

Everything else looks good.

**Comment by marianfoo** [comment]
PR is merged,
after Workflow is done and Cache is refreshed, the new packages will be visible

**Comment by iljapostnovs** [comment]
> Hey, thanks for the PR. I used your VSCodeUI5Plugin to write the VSCode crawler, so it's already there :) I hope that was ok.
> 
> Everything else looks good.

Sure, thanks!
