### ISSUE TITLE
Add new Package: ui5-i18n-excel-converter

### ISSUE THREAD

**Issue by jchirk** [ui5-community/bestofui5-data#87]
{
  "owner": "jchirk",
  "repo": "ui5-i18n-excel-converter",
  "addedToBoUI5": "2023-07-20T16:53:46.071Z",
  "type": "tooling",
  "tags": ["tooling","tool","excel","i18n","properties"]
}

**Comment by marianfoo** [comment]
Thanks for new package
It´s already added https://bestofui5.org/#/packages/ui5-i18n-excel-converter
