### ISSUE TITLE
feat: Add new Package generator-ui5-react-nest

### ISSUE THREAD

**Issue by aydin-ozcan** [ui5-community/bestofui5-data#88]
https://github.com/aydin-ozcan/generator-ui5-react-nest

- [x] Add link to your GitHub Repo in `package.json` ([example](https://github.com/ui5-community/ui5-ecosystem-showcase/blob/054d9a6ae2836fdcdef076af765b2cc292082cbd/packages/ui5-tooling-modules/package.json#L7-L11))
- [x] Add a license to your project.
- [x] Add Author to your `package.json` ([example](https://github.com/ui5-community/ui5-ecosystem-showcase/blob/054d9a6ae2836fdcdef076af765b2cc292082cbd/packages/ui5-tooling-modules/package.json#L5)).
- [x] NPM module published with current version.
- [x] `ui5.yaml` file present ([example](https://github.com/ui5-community/ui5-ecosystem-showcase/blob/main/packages/ui5-middleware-livereload/ui5.yaml))

**Comment by marianfoo** [comment]
Thanks for the PR
its already on the page:
https://bestofui5.org/#/packages/generator-ui5-react-nest
