### ISSUE TITLE
Add new Packages: SRBJSLogger, SRBInfoAndSupportJS and SRBPhysicalFeedbackJS

### ISSUE THREAD

**Issue by michaelhenningersrb** [ui5-community/bestofui5-data#96]
# Add new NPM Package

Please make sure you meet these requirements first:

## Prerequisites

- [X] Add link to your GitHub Repo in `package.json` ([example](https://github.com/ui5-community/ui5-ecosystem-showcase/blob/054d9a6ae2836fdcdef076af765b2cc292082cbd/packages/ui5-tooling-modules/package.json#L7-L11))
- [X] Add a license to your project.
- [X] Add Author to your `package.json` ([example](https://github.com/ui5-community/ui5-ecosystem-showcase/blob/054d9a6ae2836fdcdef076af765b2cc292082cbd/packages/ui5-tooling-modules/package.json#L5)).
- [X] NPM module published with current version.
- [X] `ui5.yaml` file present ([example](https://github.com/ui5-community/ui5-ecosystem-showcase/blob/main/packages/ui5-middleware-livereload/ui5.yaml))

## Pull Request

After checking the prerequisites, you can create a pull request, to edit [`sources.json`](https://github.com/ui5-community/bestofui5-data/blob/main/sources.json) with the following content:

For example, if you want to add the module `https://github.com/ui5-community/ui5-cc-md`, your commit would look like this:

```json
{
  "owner": "ui5-community",
  "repo": "ui5-cc-md",
  "addedToBoUI5": "2022-04-09T11:37:57.868Z",
  "type": "tooling",
  "tags": ["markdown"]
}
```

**owner:** is the organization or your username

**repo:** is the repo name

**addedToBoUI5:** is a timestamp with the current date

**type:** is the type of the module, please choose on of the types in the enum [BoUI5Types](https://github.com/ui5-community/bestofui5-website/blob/17eac7bc6f4f39b2b085395df3485be64bb0a864/packages/crawler/src/types.d.ts#L1)

**tags:** Here you can name relevant tags for your module, as inspiration, which are already used you can find [here](https://bestofui5-website/#/tags)

**Comment by michaelhenningersrb** [comment]
@marianfoo Here's my JSON config for three repos I want to add:


https://www.npmjs.com/package/srbjslogger
```json
{
"owner": "michaelhenningersrb",
"repo": "srbjslogger",
"addedToBoUI5": "2023-10-05T08:53:46.071Z",
"type": "library",
"tags": [ "logger","srb","log","logging"]
}
```

https://www.npmjs.com/package/srbinfoandsupportjs
```json
{
"owner": "michaelhenningersrb",
"repo": "srbinfoandsupportjs",
"addedToBoUI5": "2023-10-05T08:53:46.071Z",
"type": "library",
"tags": [ "dialog","app","info","logger","srb","log","support","qr"]
}
```

https://www.npmjs.com/package/srbphysicalfeedbackjs?activeTab=code
```json
{
"owner": "michaelhenningersrb",
"repo": "srbphysicalfeedbackjs",
"addedToBoUI5": "2023-10-05T08:53:46.071Z",
"type": "library",
"tags": [  "srb","vibrate","sound","sap","audio","beep"]
}
```

Do you need anything more? Thanks in advance!

**Comment by marianfoo** [comment]
Hi Michael,
thanks for that. Will have a look at that when i have time.

**Comment by marianfoo** [comment]
packages added, will be crawled tomorrow
